enum ItemSide {
  ATK
  DEF
  UNI
}

enum ItemSlot {
  gear
  utilities
  primary
  secondary
}

type Item {
  _id: ID!
  internal_id: String!
  name: String!
  cost: Int!
  side: ItemSide!
  slot: ItemSlot!
  createdAt: String!
  updatedAt: String!
}

extend type Query {
  csgoItems: [Item!]!
  csgoItem(id: String): Item
}

input ItemInput {
  name: String!
  cost: Int!
  side: ItemSide!
  slot: ItemSlot!
}

extend type Mutation {
  createCSGOItem(item: ItemInput): MutationReturn
  createCSGOItems(items: [ItemInput]): [MutationReturn]
}
