enum MapMode {
  de
  hs
}

type Map {
  _id: ID!
  internal_id: String!
  name: String!
  mode: MapMode!
  active: Boolean!
  createdAt: String!
  updatedAt: String!
}

extend type Query {
  csgoMaps: [Map!]!
  csgoMap(id: String): Map
}

input MapInput {
  name: String!
  mode: MapMode!
  active: Boolean!
}

extend type Mutation {
  createCSGOMap(map: MapInput): MutationReturn
  createCSGOMaps(maps: [MapInput]): [MutationReturn]
}
